name: lina_driver
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  quickalert: ^1.0.1
  lottie: ^2.3.0
  http: ^0.13.5
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.5
  bloc: ^8.1.1
  url_launcher: ^6.1.10
  image_network: ^2.5.1
  shared_preferences: ^2.1.0
  curved_navigation_bar: ^1.0.3
  geolocator: ^9.0.2
  flutter_bloc: ^8.1.2
  animated_text_kit: ^4.2.2
  flutter_polyline_points: ^1.0.0
  equatable: ^2.0.5



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
      - assets/animation/
      - assets/images/


 
  fonts:
      - family: DynaPuff
        fonts:
          - asset: assets/fonts/DynaPuff/DynaPuff-Regular.ttf
      - family: PlayfairDisplay
        fonts:
          - asset: assets/fonts/static/PlayfairDisplay-Regular.ttf
      - family: Lobster
        fonts:
          - asset: assets/fonts/Lobster/Lobster-Regular.ttf 
      - family: Oswald
        fonts:
          - asset: assets/fonts/Oswald/Oswald-Regular.ttf 
   
 
  
